# This is a basic workflow to help you get started with Actions

name: Sync with test servers

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup SSH Keys and known_hosts
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add - <<< "${{ secrets.DEPLOY_KEY }}"

    # "2244 pterodactyl@eu9.potato.tf:/"
    # Runs a set of commands using the runners shell
      - name: Sync with game servers
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mapfile -t servers < <(curl -s https://raw.githubusercontent.com/potato-tf/deploy/refs/heads/main/serverlist.json | jq -r '.servers[]')
          for i in "${servers[@]}"; do a=( $i );
          {
              rsync -a -e "ssh -p ${a[0]} -o StrictHostKeyChecking=no" ./scripts/vscripts/ ${a[1]}:/var/tf2testingserver/tf/download/scripts/vscripts/
              rsync -a -e "ssh -p ${a[0]} -o StrictHostKeyChecking=no" ./scripts/population/mvm_slick_v4a_tankextensions.pop ${a[1]}:/var/tf2testingserver/tf/download/scripts/population/

              rsync -a -e "ssh -p ${a[0]} -o StrictHostKeyChecking=no" ./assets/blimp/models/ ${a[1]}:/var/tf2testingserver/tf/download/models/
              rsync -a -e "ssh -p ${a[0]} -o StrictHostKeyChecking=no" ./assets/blimp/materials/ ${a[1]}:/var/tf2testingserver/tf/download/materials/

              rsync -a -e "ssh -p ${a[0]} -o StrictHostKeyChecking=no" ./assets/combattank/models/ ${a[1]}:/var/tf2testingserver/tf/download/models/
              rsync -a -e "ssh -p ${a[0]} -o StrictHostKeyChecking=no" ./assets/combattank/materials/ ${a[1]}:/var/tf2testingserver/tf/download/materials/

              rsync -a -e "ssh -p ${a[0]} -o StrictHostKeyChecking=no" ./assets/drilltank/models/ ${a[1]}:/var/tf2testingserver/tf/download/models/
              rsync -a -e "ssh -p ${a[0]} -o StrictHostKeyChecking=no" ./assets/drilltank/materials/ ${a[1]}:/var/tf2testingserver/tf/download/materials/

              rsync -a -e "ssh -p ${a[0]} -o StrictHostKeyChecking=no" ./assets/frontlinecart/models/ ${a[1]}:/var/tf2testingserver/tf/download/models/
              rsync -a -e "ssh -p ${a[0]} -o StrictHostKeyChecking=no" ./assets/frontlinecart/materials/ ${a[1]}:/var/tf2testingserver/tf/download/materials/

              rsync -a -e "ssh -p ${a[0]} -o StrictHostKeyChecking=no" ./assets/painttank/models/ ${a[1]}:/var/tf2testingserver/tf/download/models/
              rsync -a -e "ssh -p ${a[0]} -o StrictHostKeyChecking=no" ./assets/painttank/materials/ ${a[1]}:/var/tf2testingserver/tf/download/materials/

              rsync -a -e "ssh -p ${a[0]} -o StrictHostKeyChecking=no" ./assets/paratank/models/ ${a[1]}:/var/tf2testingserver/tf/download/models/

              rsync -a -e "ssh -p ${a[0]} -o StrictHostKeyChecking=no" ./assets/redtank/models/ ${a[1]}:/var/tf2testingserver/tf/download/models/
              rsync -a -e "ssh -p ${a[0]} -o StrictHostKeyChecking=no" ./assets/redtank/materials/ ${a[1]}:/var/tf2testingserver/tf/download/materials/

              rsync -a -e "ssh -p ${a[0]} -o StrictHostKeyChecking=no" ./assets/stickytank/models/ ${a[1]}:/var/tf2testingserver/tf/download/models/
              rsync -a -e "ssh -p ${a[0]} -o StrictHostKeyChecking=no" ./assets/stickytank/materials/ ${a[1]}:/var/tf2testingserver/tf/download/materials/

              rsync -a -e "ssh -p ${a[0]} -o StrictHostKeyChecking=no" ./assets/tankdozer/models/ ${a[1]}:/var/tf2testingserver/tf/download/models/
              rsync -a -e "ssh -p ${a[0]} -o StrictHostKeyChecking=no" ./assets/tankdozer/materials/ ${a[1]}:/var/tf2testingserver/tf/download/materials/

              rsync -a -e "ssh -p ${a[0]} -o StrictHostKeyChecking=no" ./assets/ubertank/models/ ${a[1]}:/var/tf2testingserver/tf/download/models/
              rsync -a -e "ssh -p ${a[0]} -o StrictHostKeyChecking=no" ./assets/ubertank/materials/ ${a[1]}:/var/tf2testingserver/tf/download/materials/

              rsync -a -e "ssh -p ${a[0]} -o StrictHostKeyChecking=no" ./assets/vactank/models/ ${a[1]}:/var/tf2testingserver/tf/download/models/
          } &
          done
          wait
